### ISSUE TITLE
How to pass conditional --record CLI flag

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-circleci-orb#2]
- based on `record` parameter?
- and it would be nice to check if the environment variable `CYPRESS_RECORD_KEY` is present too maybe

**Comment by a-tokyo** [comment]
@bahmutov Thanks for your response! 

I checked the documentation. There's no possible way to conditionally record the tests.

In my case, I want record staging branch tests only. This is not possible atm
