### ISSUE TITLE
nomenclature of job names, parameters, etc

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress-example-circleci-orb#4]
https://github.com/cypress-io/circleci-orb-test/blob/0314523f0bbff82d4242b80d8371f08544bcd878/.circleci/config.yml#L8

Instead of:

- `runner/e2e`

Could have:

- `runner/run`

This would bring it better into parity with `cypress run`.

We could also rename the orb to be `cypress/cypress` as you originally had it.

Then it would be:

- `cypress/run`

Which is the closest to what we have.

I'm trying to think if we have any other "commands/jobs/whatever" besides `run`. If we did exposed other things like caching or whatever then it would make sense - but those all would likely parameters of the job right?

What about handling things like `browsers`? Is that just another option to `cypress/run`?

```
cypress/run:
	browsers: 'whatever'
	node: 10
	record: true
	group: me
```

**Edit:**

I know that this is super premature, but if we did release like a Cypress runner for just node (and not browser testing) - what would it be called?

Would it be better to namespace like this: `cypress/browser` vs `cypress/node` or something like `cypress/cypress` and then `cypress/node` with its own job name like: `node/run`

**Edit 2:**

Should we separate out the jobs into smaller pieces? Like `cypress/install` or `cypress/cache` or whatever? 

If we did the install job then users could use it independently from the `cypress/run` and likely better cache, etc by doing that job first, and then running `cypress/run` later. Since `cypress/run` would already check to see if its installed it should "just work". `cypress/install` would be optional though.

**Comment by bahmutov** [comment]
done
